// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/types/block.proto

package tendermint.types;

public final class BlockOuterClass {
  private BlockOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tendermint.types.Block)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
     * @return The header.
     */
    Types.Header getHeader();
    /**
     * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
     */
    Types.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
     * @return The data.
     */
    Types.Data getData();
    /**
     * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
     */
    Types.DataOrBuilder getDataOrBuilder();

    /**
     * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
     * @return Whether the evidence field is set.
     */
    boolean hasEvidence();
    /**
     * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
     * @return The evidence.
     */
    EvidenceOuterClass.EvidenceList getEvidence();
    /**
     * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
     */
    EvidenceOuterClass.EvidenceListOrBuilder getEvidenceOrBuilder();

    /**
     * <code>.tendermint.types.Commit last_commit = 4;</code>
     * @return Whether the lastCommit field is set.
     */
    boolean hasLastCommit();
    /**
     * <code>.tendermint.types.Commit last_commit = 4;</code>
     * @return The lastCommit.
     */
    Types.Commit getLastCommit();
    /**
     * <code>.tendermint.types.Commit last_commit = 4;</code>
     */
    Types.CommitOrBuilder getLastCommitOrBuilder();
  }
  /**
   * Protobuf type {@code tendermint.types.Block}
   */
  public static final class Block extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tendermint.types.Block)
      BlockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Block.newBuilder() to construct.
    private Block(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Block() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Block();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Block(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Types.Header.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(Types.Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              Types.Data.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(Types.Data.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              EvidenceOuterClass.EvidenceList.Builder subBuilder = null;
              if (evidence_ != null) {
                subBuilder = evidence_.toBuilder();
              }
              evidence_ = input.readMessage(EvidenceOuterClass.EvidenceList.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(evidence_);
                evidence_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              Types.Commit.Builder subBuilder = null;
              if (lastCommit_ != null) {
                subBuilder = lastCommit_.toBuilder();
              }
              lastCommit_ = input.readMessage(Types.Commit.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lastCommit_);
                lastCommit_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BlockOuterClass.internal_static_tendermint_types_Block_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BlockOuterClass.internal_static_tendermint_types_Block_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Block.class, Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private Types.Header header_;
    /**
     * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the header field is set.
     */
    @Override
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
     * @return The header.
     */
    @Override
    public Types.Header getHeader() {
      return header_ == null ? Types.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
     */
    @Override
    public Types.HeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private Types.Data data_;
    /**
     * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
     * @return Whether the data field is set.
     */
    @Override
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
     * @return The data.
     */
    @Override
    public Types.Data getData() {
      return data_ == null ? Types.Data.getDefaultInstance() : data_;
    }
    /**
     * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
     */
    @Override
    public Types.DataOrBuilder getDataOrBuilder() {
      return getData();
    }

    public static final int EVIDENCE_FIELD_NUMBER = 3;
    private EvidenceOuterClass.EvidenceList evidence_;
    /**
     * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
     * @return Whether the evidence field is set.
     */
    @Override
    public boolean hasEvidence() {
      return evidence_ != null;
    }
    /**
     * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
     * @return The evidence.
     */
    @Override
    public EvidenceOuterClass.EvidenceList getEvidence() {
      return evidence_ == null ? EvidenceOuterClass.EvidenceList.getDefaultInstance() : evidence_;
    }
    /**
     * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
     */
    @Override
    public EvidenceOuterClass.EvidenceListOrBuilder getEvidenceOrBuilder() {
      return getEvidence();
    }

    public static final int LAST_COMMIT_FIELD_NUMBER = 4;
    private Types.Commit lastCommit_;
    /**
     * <code>.tendermint.types.Commit last_commit = 4;</code>
     * @return Whether the lastCommit field is set.
     */
    @Override
    public boolean hasLastCommit() {
      return lastCommit_ != null;
    }
    /**
     * <code>.tendermint.types.Commit last_commit = 4;</code>
     * @return The lastCommit.
     */
    @Override
    public Types.Commit getLastCommit() {
      return lastCommit_ == null ? Types.Commit.getDefaultInstance() : lastCommit_;
    }
    /**
     * <code>.tendermint.types.Commit last_commit = 4;</code>
     */
    @Override
    public Types.CommitOrBuilder getLastCommitOrBuilder() {
      return getLastCommit();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (data_ != null) {
        output.writeMessage(2, getData());
      }
      if (evidence_ != null) {
        output.writeMessage(3, getEvidence());
      }
      if (lastCommit_ != null) {
        output.writeMessage(4, getLastCommit());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getData());
      }
      if (evidence_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getEvidence());
      }
      if (lastCommit_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getLastCommit());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Block)) {
        return super.equals(obj);
      }
      Block other = (Block) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (hasEvidence() != other.hasEvidence()) return false;
      if (hasEvidence()) {
        if (!getEvidence()
            .equals(other.getEvidence())) return false;
      }
      if (hasLastCommit() != other.hasLastCommit()) return false;
      if (hasLastCommit()) {
        if (!getLastCommit()
            .equals(other.getLastCommit())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasEvidence()) {
        hash = (37 * hash) + EVIDENCE_FIELD_NUMBER;
        hash = (53 * hash) + getEvidence().hashCode();
      }
      if (hasLastCommit()) {
        hash = (37 * hash) + LAST_COMMIT_FIELD_NUMBER;
        hash = (53 * hash) + getLastCommit().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Block parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Block parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Block parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Block parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Block parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Block parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Block parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Block parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Block parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Block parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Block parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Block parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Block prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tendermint.types.Block}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tendermint.types.Block)
        BlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BlockOuterClass.internal_static_tendermint_types_Block_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BlockOuterClass.internal_static_tendermint_types_Block_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Block.class, Builder.class);
      }

      // Construct using tendermint.types.BlockOuterClass.Block.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        if (evidenceBuilder_ == null) {
          evidence_ = null;
        } else {
          evidence_ = null;
          evidenceBuilder_ = null;
        }
        if (lastCommitBuilder_ == null) {
          lastCommit_ = null;
        } else {
          lastCommit_ = null;
          lastCommitBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BlockOuterClass.internal_static_tendermint_types_Block_descriptor;
      }

      @Override
      public Block getDefaultInstanceForType() {
        return Block.getDefaultInstance();
      }

      @Override
      public Block build() {
        Block result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Block buildPartial() {
        Block result = new Block(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        if (evidenceBuilder_ == null) {
          result.evidence_ = evidence_;
        } else {
          result.evidence_ = evidenceBuilder_.build();
        }
        if (lastCommitBuilder_ == null) {
          result.lastCommit_ = lastCommit_;
        } else {
          result.lastCommit_ = lastCommitBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Block) {
          return mergeFrom((Block)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Block other) {
        if (other == Block.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        if (other.hasEvidence()) {
          mergeEvidence(other.getEvidence());
        }
        if (other.hasLastCommit()) {
          mergeLastCommit(other.getLastCommit());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Block parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Block) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Types.Header header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Types.Header, Types.Header.Builder, Types.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
       * @return The header.
       */
      public Types.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? Types.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setHeader(Types.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setHeader(
          Types.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergeHeader(Types.Header value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              Types.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Types.Header.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Types.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              Types.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.tendermint.types.Header header = 1 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Types.Header, Types.Header.Builder, Types.HeaderOrBuilder>
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Types.Header, Types.Header.Builder, Types.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private Types.Data data_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Types.Data, Types.Data.Builder, Types.DataOrBuilder> dataBuilder_;
      /**
       * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
       * @return Whether the data field is set.
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
      /**
       * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
       * @return The data.
       */
      public Types.Data getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? Types.Data.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setData(Types.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setData(
          Types.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergeData(Types.Data value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
              Types.Data.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Types.Data.Builder getDataBuilder() {
        
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Types.DataOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              Types.Data.getDefaultInstance() : data_;
        }
      }
      /**
       * <code>.tendermint.types.Data data = 2 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Types.Data, Types.Data.Builder, Types.DataOrBuilder>
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Types.Data, Types.Data.Builder, Types.DataOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      private EvidenceOuterClass.EvidenceList evidence_;
      private com.google.protobuf.SingleFieldBuilderV3<
          EvidenceOuterClass.EvidenceList, EvidenceOuterClass.EvidenceList.Builder, EvidenceOuterClass.EvidenceListOrBuilder> evidenceBuilder_;
      /**
       * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
       * @return Whether the evidence field is set.
       */
      public boolean hasEvidence() {
        return evidenceBuilder_ != null || evidence_ != null;
      }
      /**
       * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
       * @return The evidence.
       */
      public EvidenceOuterClass.EvidenceList getEvidence() {
        if (evidenceBuilder_ == null) {
          return evidence_ == null ? EvidenceOuterClass.EvidenceList.getDefaultInstance() : evidence_;
        } else {
          return evidenceBuilder_.getMessage();
        }
      }
      /**
       * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setEvidence(EvidenceOuterClass.EvidenceList value) {
        if (evidenceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          evidence_ = value;
          onChanged();
        } else {
          evidenceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setEvidence(
          EvidenceOuterClass.EvidenceList.Builder builderForValue) {
        if (evidenceBuilder_ == null) {
          evidence_ = builderForValue.build();
          onChanged();
        } else {
          evidenceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergeEvidence(EvidenceOuterClass.EvidenceList value) {
        if (evidenceBuilder_ == null) {
          if (evidence_ != null) {
            evidence_ =
              EvidenceOuterClass.EvidenceList.newBuilder(evidence_).mergeFrom(value).buildPartial();
          } else {
            evidence_ = value;
          }
          onChanged();
        } else {
          evidenceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearEvidence() {
        if (evidenceBuilder_ == null) {
          evidence_ = null;
          onChanged();
        } else {
          evidence_ = null;
          evidenceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
       */
      public EvidenceOuterClass.EvidenceList.Builder getEvidenceBuilder() {
        
        onChanged();
        return getEvidenceFieldBuilder().getBuilder();
      }
      /**
       * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
       */
      public EvidenceOuterClass.EvidenceListOrBuilder getEvidenceOrBuilder() {
        if (evidenceBuilder_ != null) {
          return evidenceBuilder_.getMessageOrBuilder();
        } else {
          return evidence_ == null ?
              EvidenceOuterClass.EvidenceList.getDefaultInstance() : evidence_;
        }
      }
      /**
       * <code>.tendermint.types.EvidenceList evidence = 3 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          EvidenceOuterClass.EvidenceList, EvidenceOuterClass.EvidenceList.Builder, EvidenceOuterClass.EvidenceListOrBuilder>
          getEvidenceFieldBuilder() {
        if (evidenceBuilder_ == null) {
          evidenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              EvidenceOuterClass.EvidenceList, EvidenceOuterClass.EvidenceList.Builder, EvidenceOuterClass.EvidenceListOrBuilder>(
                  getEvidence(),
                  getParentForChildren(),
                  isClean());
          evidence_ = null;
        }
        return evidenceBuilder_;
      }

      private Types.Commit lastCommit_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Types.Commit, Types.Commit.Builder, Types.CommitOrBuilder> lastCommitBuilder_;
      /**
       * <code>.tendermint.types.Commit last_commit = 4;</code>
       * @return Whether the lastCommit field is set.
       */
      public boolean hasLastCommit() {
        return lastCommitBuilder_ != null || lastCommit_ != null;
      }
      /**
       * <code>.tendermint.types.Commit last_commit = 4;</code>
       * @return The lastCommit.
       */
      public Types.Commit getLastCommit() {
        if (lastCommitBuilder_ == null) {
          return lastCommit_ == null ? Types.Commit.getDefaultInstance() : lastCommit_;
        } else {
          return lastCommitBuilder_.getMessage();
        }
      }
      /**
       * <code>.tendermint.types.Commit last_commit = 4;</code>
       */
      public Builder setLastCommit(Types.Commit value) {
        if (lastCommitBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lastCommit_ = value;
          onChanged();
        } else {
          lastCommitBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Commit last_commit = 4;</code>
       */
      public Builder setLastCommit(
          Types.Commit.Builder builderForValue) {
        if (lastCommitBuilder_ == null) {
          lastCommit_ = builderForValue.build();
          onChanged();
        } else {
          lastCommitBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Commit last_commit = 4;</code>
       */
      public Builder mergeLastCommit(Types.Commit value) {
        if (lastCommitBuilder_ == null) {
          if (lastCommit_ != null) {
            lastCommit_ =
              Types.Commit.newBuilder(lastCommit_).mergeFrom(value).buildPartial();
          } else {
            lastCommit_ = value;
          }
          onChanged();
        } else {
          lastCommitBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Commit last_commit = 4;</code>
       */
      public Builder clearLastCommit() {
        if (lastCommitBuilder_ == null) {
          lastCommit_ = null;
          onChanged();
        } else {
          lastCommit_ = null;
          lastCommitBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Commit last_commit = 4;</code>
       */
      public Types.Commit.Builder getLastCommitBuilder() {
        
        onChanged();
        return getLastCommitFieldBuilder().getBuilder();
      }
      /**
       * <code>.tendermint.types.Commit last_commit = 4;</code>
       */
      public Types.CommitOrBuilder getLastCommitOrBuilder() {
        if (lastCommitBuilder_ != null) {
          return lastCommitBuilder_.getMessageOrBuilder();
        } else {
          return lastCommit_ == null ?
              Types.Commit.getDefaultInstance() : lastCommit_;
        }
      }
      /**
       * <code>.tendermint.types.Commit last_commit = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Types.Commit, Types.Commit.Builder, Types.CommitOrBuilder>
          getLastCommitFieldBuilder() {
        if (lastCommitBuilder_ == null) {
          lastCommitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Types.Commit, Types.Commit.Builder, Types.CommitOrBuilder>(
                  getLastCommit(),
                  getParentForChildren(),
                  isClean());
          lastCommit_ = null;
        }
        return lastCommitBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tendermint.types.Block)
    }

    // @@protoc_insertion_point(class_scope:tendermint.types.Block)
    private static final Block DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Block();
    }

    public static Block getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Block>
        PARSER = new com.google.protobuf.AbstractParser<Block>() {
      @Override
      public Block parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Block(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Block> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Block> getParserForType() {
      return PARSER;
    }

    @Override
    public Block getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tendermint_types_Block_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tendermint_types_Block_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034tendermint/types/block.proto\022\020tendermi" +
      "nt.types\032\024gogoproto/gogo.proto\032\034tendermi" +
      "nt/types/types.proto\032\037tendermint/types/e" +
      "vidence.proto\"\312\001\n\005Block\022.\n\006header\030\001 \001(\0132" +
      "\030.tendermint.types.HeaderB\004\310\336\037\000\022*\n\004data\030" +
      "\002 \001(\0132\026.tendermint.types.DataB\004\310\336\037\000\0226\n\010e" +
      "vidence\030\003 \001(\0132\036.tendermint.types.Evidenc" +
      "eListB\004\310\336\037\000\022-\n\013last_commit\030\004 \001(\0132\030.tende" +
      "rmint.types.CommitB9Z7github.com/tenderm" +
      "int/tendermint/proto/tendermint/typesb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf2.GoGoProtos.getDescriptor(),
          Types.getDescriptor(),
          EvidenceOuterClass.getDescriptor(),
        });
    internal_static_tendermint_types_Block_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tendermint_types_Block_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tendermint_types_Block_descriptor,
        new String[] { "Header", "Data", "Evidence", "LastCommit", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf2.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf2.GoGoProtos.getDescriptor();
    Types.getDescriptor();
    EvidenceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
