// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/types/validator.proto

package tendermint.types;

public final class ValidatorOuterClass {
  private ValidatorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ValidatorSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tendermint.types.ValidatorSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .tendermint.types.Validator validators = 1;</code>
     */
    java.util.List<Validator>
        getValidatorsList();
    /**
     * <code>repeated .tendermint.types.Validator validators = 1;</code>
     */
    Validator getValidators(int index);
    /**
     * <code>repeated .tendermint.types.Validator validators = 1;</code>
     */
    int getValidatorsCount();
    /**
     * <code>repeated .tendermint.types.Validator validators = 1;</code>
     */
    java.util.List<? extends ValidatorOrBuilder>
        getValidatorsOrBuilderList();
    /**
     * <code>repeated .tendermint.types.Validator validators = 1;</code>
     */
    ValidatorOrBuilder getValidatorsOrBuilder(
        int index);

    /**
     * <code>.tendermint.types.Validator proposer = 2;</code>
     * @return Whether the proposer field is set.
     */
    boolean hasProposer();
    /**
     * <code>.tendermint.types.Validator proposer = 2;</code>
     * @return The proposer.
     */
    Validator getProposer();
    /**
     * <code>.tendermint.types.Validator proposer = 2;</code>
     */
    ValidatorOrBuilder getProposerOrBuilder();

    /**
     * <code>int64 total_voting_power = 3;</code>
     * @return The totalVotingPower.
     */
    long getTotalVotingPower();
  }
  /**
   * Protobuf type {@code tendermint.types.ValidatorSet}
   */
  public static final class ValidatorSet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tendermint.types.ValidatorSet)
      ValidatorSetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValidatorSet.newBuilder() to construct.
    private ValidatorSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValidatorSet() {
      validators_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ValidatorSet();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ValidatorSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                validators_ = new java.util.ArrayList<Validator>();
                mutable_bitField0_ |= 0x00000001;
              }
              validators_.add(
                  input.readMessage(Validator.parser(), extensionRegistry));
              break;
            }
            case 18: {
              Validator.Builder subBuilder = null;
              if (proposer_ != null) {
                subBuilder = proposer_.toBuilder();
              }
              proposer_ = input.readMessage(Validator.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(proposer_);
                proposer_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              totalVotingPower_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          validators_ = java.util.Collections.unmodifiableList(validators_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ValidatorOuterClass.internal_static_tendermint_types_ValidatorSet_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ValidatorOuterClass.internal_static_tendermint_types_ValidatorSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ValidatorSet.class, Builder.class);
    }

    public static final int VALIDATORS_FIELD_NUMBER = 1;
    private java.util.List<Validator> validators_;
    /**
     * <code>repeated .tendermint.types.Validator validators = 1;</code>
     */
    @Override
    public java.util.List<Validator> getValidatorsList() {
      return validators_;
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1;</code>
     */
    @Override
    public java.util.List<? extends ValidatorOrBuilder>
        getValidatorsOrBuilderList() {
      return validators_;
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1;</code>
     */
    @Override
    public int getValidatorsCount() {
      return validators_.size();
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1;</code>
     */
    @Override
    public Validator getValidators(int index) {
      return validators_.get(index);
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1;</code>
     */
    @Override
    public ValidatorOrBuilder getValidatorsOrBuilder(
        int index) {
      return validators_.get(index);
    }

    public static final int PROPOSER_FIELD_NUMBER = 2;
    private Validator proposer_;
    /**
     * <code>.tendermint.types.Validator proposer = 2;</code>
     * @return Whether the proposer field is set.
     */
    @Override
    public boolean hasProposer() {
      return proposer_ != null;
    }
    /**
     * <code>.tendermint.types.Validator proposer = 2;</code>
     * @return The proposer.
     */
    @Override
    public Validator getProposer() {
      return proposer_ == null ? Validator.getDefaultInstance() : proposer_;
    }
    /**
     * <code>.tendermint.types.Validator proposer = 2;</code>
     */
    @Override
    public ValidatorOrBuilder getProposerOrBuilder() {
      return getProposer();
    }

    public static final int TOTAL_VOTING_POWER_FIELD_NUMBER = 3;
    private long totalVotingPower_;
    /**
     * <code>int64 total_voting_power = 3;</code>
     * @return The totalVotingPower.
     */
    @Override
    public long getTotalVotingPower() {
      return totalVotingPower_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < validators_.size(); i++) {
        output.writeMessage(1, validators_.get(i));
      }
      if (proposer_ != null) {
        output.writeMessage(2, getProposer());
      }
      if (totalVotingPower_ != 0L) {
        output.writeInt64(3, totalVotingPower_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < validators_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, validators_.get(i));
      }
      if (proposer_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getProposer());
      }
      if (totalVotingPower_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, totalVotingPower_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ValidatorSet)) {
        return super.equals(obj);
      }
      ValidatorSet other = (ValidatorSet) obj;

      if (!getValidatorsList()
          .equals(other.getValidatorsList())) return false;
      if (hasProposer() != other.hasProposer()) return false;
      if (hasProposer()) {
        if (!getProposer()
            .equals(other.getProposer())) return false;
      }
      if (getTotalVotingPower()
          != other.getTotalVotingPower()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValidatorsCount() > 0) {
        hash = (37 * hash) + VALIDATORS_FIELD_NUMBER;
        hash = (53 * hash) + getValidatorsList().hashCode();
      }
      if (hasProposer()) {
        hash = (37 * hash) + PROPOSER_FIELD_NUMBER;
        hash = (53 * hash) + getProposer().hashCode();
      }
      hash = (37 * hash) + TOTAL_VOTING_POWER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalVotingPower());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ValidatorSet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ValidatorSet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ValidatorSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ValidatorSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ValidatorSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ValidatorSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ValidatorSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ValidatorSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ValidatorSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ValidatorSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ValidatorSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ValidatorSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ValidatorSet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tendermint.types.ValidatorSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tendermint.types.ValidatorSet)
        ValidatorSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ValidatorOuterClass.internal_static_tendermint_types_ValidatorSet_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ValidatorOuterClass.internal_static_tendermint_types_ValidatorSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ValidatorSet.class, Builder.class);
      }

      // Construct using tendermint.types.ValidatorOuterClass.ValidatorSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getValidatorsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (validatorsBuilder_ == null) {
          validators_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          validatorsBuilder_.clear();
        }
        if (proposerBuilder_ == null) {
          proposer_ = null;
        } else {
          proposer_ = null;
          proposerBuilder_ = null;
        }
        totalVotingPower_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ValidatorOuterClass.internal_static_tendermint_types_ValidatorSet_descriptor;
      }

      @Override
      public ValidatorSet getDefaultInstanceForType() {
        return ValidatorSet.getDefaultInstance();
      }

      @Override
      public ValidatorSet build() {
        ValidatorSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ValidatorSet buildPartial() {
        ValidatorSet result = new ValidatorSet(this);
        int from_bitField0_ = bitField0_;
        if (validatorsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            validators_ = java.util.Collections.unmodifiableList(validators_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.validators_ = validators_;
        } else {
          result.validators_ = validatorsBuilder_.build();
        }
        if (proposerBuilder_ == null) {
          result.proposer_ = proposer_;
        } else {
          result.proposer_ = proposerBuilder_.build();
        }
        result.totalVotingPower_ = totalVotingPower_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ValidatorSet) {
          return mergeFrom((ValidatorSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ValidatorSet other) {
        if (other == ValidatorSet.getDefaultInstance()) return this;
        if (validatorsBuilder_ == null) {
          if (!other.validators_.isEmpty()) {
            if (validators_.isEmpty()) {
              validators_ = other.validators_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValidatorsIsMutable();
              validators_.addAll(other.validators_);
            }
            onChanged();
          }
        } else {
          if (!other.validators_.isEmpty()) {
            if (validatorsBuilder_.isEmpty()) {
              validatorsBuilder_.dispose();
              validatorsBuilder_ = null;
              validators_ = other.validators_;
              bitField0_ = (bitField0_ & ~0x00000001);
              validatorsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getValidatorsFieldBuilder() : null;
            } else {
              validatorsBuilder_.addAllMessages(other.validators_);
            }
          }
        }
        if (other.hasProposer()) {
          mergeProposer(other.getProposer());
        }
        if (other.getTotalVotingPower() != 0L) {
          setTotalVotingPower(other.getTotalVotingPower());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ValidatorSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ValidatorSet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Validator> validators_ =
        java.util.Collections.emptyList();
      private void ensureValidatorsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          validators_ = new java.util.ArrayList<Validator>(validators_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Validator, Validator.Builder, ValidatorOrBuilder> validatorsBuilder_;

      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public java.util.List<Validator> getValidatorsList() {
        if (validatorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(validators_);
        } else {
          return validatorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public int getValidatorsCount() {
        if (validatorsBuilder_ == null) {
          return validators_.size();
        } else {
          return validatorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Validator getValidators(int index) {
        if (validatorsBuilder_ == null) {
          return validators_.get(index);
        } else {
          return validatorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Builder setValidators(
          int index, Validator value) {
        if (validatorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValidatorsIsMutable();
          validators_.set(index, value);
          onChanged();
        } else {
          validatorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Builder setValidators(
          int index, Validator.Builder builderForValue) {
        if (validatorsBuilder_ == null) {
          ensureValidatorsIsMutable();
          validators_.set(index, builderForValue.build());
          onChanged();
        } else {
          validatorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Builder addValidators(Validator value) {
        if (validatorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValidatorsIsMutable();
          validators_.add(value);
          onChanged();
        } else {
          validatorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Builder addValidators(
          int index, Validator value) {
        if (validatorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValidatorsIsMutable();
          validators_.add(index, value);
          onChanged();
        } else {
          validatorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Builder addValidators(
          Validator.Builder builderForValue) {
        if (validatorsBuilder_ == null) {
          ensureValidatorsIsMutable();
          validators_.add(builderForValue.build());
          onChanged();
        } else {
          validatorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Builder addValidators(
          int index, Validator.Builder builderForValue) {
        if (validatorsBuilder_ == null) {
          ensureValidatorsIsMutable();
          validators_.add(index, builderForValue.build());
          onChanged();
        } else {
          validatorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Builder addAllValidators(
          Iterable<? extends Validator> values) {
        if (validatorsBuilder_ == null) {
          ensureValidatorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, validators_);
          onChanged();
        } else {
          validatorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Builder clearValidators() {
        if (validatorsBuilder_ == null) {
          validators_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          validatorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Builder removeValidators(int index) {
        if (validatorsBuilder_ == null) {
          ensureValidatorsIsMutable();
          validators_.remove(index);
          onChanged();
        } else {
          validatorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Validator.Builder getValidatorsBuilder(
          int index) {
        return getValidatorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public ValidatorOrBuilder getValidatorsOrBuilder(
          int index) {
        if (validatorsBuilder_ == null) {
          return validators_.get(index);  } else {
          return validatorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public java.util.List<? extends ValidatorOrBuilder>
           getValidatorsOrBuilderList() {
        if (validatorsBuilder_ != null) {
          return validatorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(validators_);
        }
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Validator.Builder addValidatorsBuilder() {
        return getValidatorsFieldBuilder().addBuilder(
            Validator.getDefaultInstance());
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public Validator.Builder addValidatorsBuilder(
          int index) {
        return getValidatorsFieldBuilder().addBuilder(
            index, Validator.getDefaultInstance());
      }
      /**
       * <code>repeated .tendermint.types.Validator validators = 1;</code>
       */
      public java.util.List<Validator.Builder>
           getValidatorsBuilderList() {
        return getValidatorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Validator, Validator.Builder, ValidatorOrBuilder>
          getValidatorsFieldBuilder() {
        if (validatorsBuilder_ == null) {
          validatorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Validator, Validator.Builder, ValidatorOrBuilder>(
                  validators_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          validators_ = null;
        }
        return validatorsBuilder_;
      }

      private Validator proposer_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Validator, Validator.Builder, ValidatorOrBuilder> proposerBuilder_;
      /**
       * <code>.tendermint.types.Validator proposer = 2;</code>
       * @return Whether the proposer field is set.
       */
      public boolean hasProposer() {
        return proposerBuilder_ != null || proposer_ != null;
      }
      /**
       * <code>.tendermint.types.Validator proposer = 2;</code>
       * @return The proposer.
       */
      public Validator getProposer() {
        if (proposerBuilder_ == null) {
          return proposer_ == null ? Validator.getDefaultInstance() : proposer_;
        } else {
          return proposerBuilder_.getMessage();
        }
      }
      /**
       * <code>.tendermint.types.Validator proposer = 2;</code>
       */
      public Builder setProposer(Validator value) {
        if (proposerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          proposer_ = value;
          onChanged();
        } else {
          proposerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Validator proposer = 2;</code>
       */
      public Builder setProposer(
          Validator.Builder builderForValue) {
        if (proposerBuilder_ == null) {
          proposer_ = builderForValue.build();
          onChanged();
        } else {
          proposerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Validator proposer = 2;</code>
       */
      public Builder mergeProposer(Validator value) {
        if (proposerBuilder_ == null) {
          if (proposer_ != null) {
            proposer_ =
              Validator.newBuilder(proposer_).mergeFrom(value).buildPartial();
          } else {
            proposer_ = value;
          }
          onChanged();
        } else {
          proposerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Validator proposer = 2;</code>
       */
      public Builder clearProposer() {
        if (proposerBuilder_ == null) {
          proposer_ = null;
          onChanged();
        } else {
          proposer_ = null;
          proposerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tendermint.types.Validator proposer = 2;</code>
       */
      public Validator.Builder getProposerBuilder() {
        
        onChanged();
        return getProposerFieldBuilder().getBuilder();
      }
      /**
       * <code>.tendermint.types.Validator proposer = 2;</code>
       */
      public ValidatorOrBuilder getProposerOrBuilder() {
        if (proposerBuilder_ != null) {
          return proposerBuilder_.getMessageOrBuilder();
        } else {
          return proposer_ == null ?
              Validator.getDefaultInstance() : proposer_;
        }
      }
      /**
       * <code>.tendermint.types.Validator proposer = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Validator, Validator.Builder, ValidatorOrBuilder>
          getProposerFieldBuilder() {
        if (proposerBuilder_ == null) {
          proposerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Validator, Validator.Builder, ValidatorOrBuilder>(
                  getProposer(),
                  getParentForChildren(),
                  isClean());
          proposer_ = null;
        }
        return proposerBuilder_;
      }

      private long totalVotingPower_ ;
      /**
       * <code>int64 total_voting_power = 3;</code>
       * @return The totalVotingPower.
       */
      @Override
      public long getTotalVotingPower() {
        return totalVotingPower_;
      }
      /**
       * <code>int64 total_voting_power = 3;</code>
       * @param value The totalVotingPower to set.
       * @return This builder for chaining.
       */
      public Builder setTotalVotingPower(long value) {
        
        totalVotingPower_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 total_voting_power = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalVotingPower() {
        
        totalVotingPower_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tendermint.types.ValidatorSet)
    }

    // @@protoc_insertion_point(class_scope:tendermint.types.ValidatorSet)
    private static final ValidatorSet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ValidatorSet();
    }

    public static ValidatorSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValidatorSet>
        PARSER = new com.google.protobuf.AbstractParser<ValidatorSet>() {
      @Override
      public ValidatorSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValidatorSet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValidatorSet> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ValidatorSet> getParserForType() {
      return PARSER;
    }

    @Override
    public ValidatorSet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValidatorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tendermint.types.Validator)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes address = 1;</code>
     * @return The address.
     */
    com.google.protobuf.ByteString getAddress();

    /**
     * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
     * @return Whether the pubKey field is set.
     */
    boolean hasPubKey();
    /**
     * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
     * @return The pubKey.
     */
    tendermint.crypto.Keys.PublicKey getPubKey();
    /**
     * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
     */
    tendermint.crypto.Keys.PublicKeyOrBuilder getPubKeyOrBuilder();

    /**
     * <code>int64 voting_power = 3;</code>
     * @return The votingPower.
     */
    long getVotingPower();

    /**
     * <code>int64 proposer_priority = 4;</code>
     * @return The proposerPriority.
     */
    long getProposerPriority();
  }
  /**
   * Protobuf type {@code tendermint.types.Validator}
   */
  public static final class Validator extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tendermint.types.Validator)
      ValidatorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Validator.newBuilder() to construct.
    private Validator(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Validator() {
      address_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Validator();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Validator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              address_ = input.readBytes();
              break;
            }
            case 18: {
              tendermint.crypto.Keys.PublicKey.Builder subBuilder = null;
              if (pubKey_ != null) {
                subBuilder = pubKey_.toBuilder();
              }
              pubKey_ = input.readMessage(tendermint.crypto.Keys.PublicKey.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pubKey_);
                pubKey_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              votingPower_ = input.readInt64();
              break;
            }
            case 32: {

              proposerPriority_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ValidatorOuterClass.internal_static_tendermint_types_Validator_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ValidatorOuterClass.internal_static_tendermint_types_Validator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Validator.class, Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString address_;
    /**
     * <code>bytes address = 1;</code>
     * @return The address.
     */
    @Override
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    public static final int PUB_KEY_FIELD_NUMBER = 2;
    private tendermint.crypto.Keys.PublicKey pubKey_;
    /**
     * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
     * @return Whether the pubKey field is set.
     */
    @Override
    public boolean hasPubKey() {
      return pubKey_ != null;
    }
    /**
     * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
     * @return The pubKey.
     */
    @Override
    public tendermint.crypto.Keys.PublicKey getPubKey() {
      return pubKey_ == null ? tendermint.crypto.Keys.PublicKey.getDefaultInstance() : pubKey_;
    }
    /**
     * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
     */
    @Override
    public tendermint.crypto.Keys.PublicKeyOrBuilder getPubKeyOrBuilder() {
      return getPubKey();
    }

    public static final int VOTING_POWER_FIELD_NUMBER = 3;
    private long votingPower_;
    /**
     * <code>int64 voting_power = 3;</code>
     * @return The votingPower.
     */
    @Override
    public long getVotingPower() {
      return votingPower_;
    }

    public static final int PROPOSER_PRIORITY_FIELD_NUMBER = 4;
    private long proposerPriority_;
    /**
     * <code>int64 proposer_priority = 4;</code>
     * @return The proposerPriority.
     */
    @Override
    public long getProposerPriority() {
      return proposerPriority_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!address_.isEmpty()) {
        output.writeBytes(1, address_);
      }
      if (pubKey_ != null) {
        output.writeMessage(2, getPubKey());
      }
      if (votingPower_ != 0L) {
        output.writeInt64(3, votingPower_);
      }
      if (proposerPriority_ != 0L) {
        output.writeInt64(4, proposerPriority_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!address_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, address_);
      }
      if (pubKey_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPubKey());
      }
      if (votingPower_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, votingPower_);
      }
      if (proposerPriority_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, proposerPriority_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Validator)) {
        return super.equals(obj);
      }
      Validator other = (Validator) obj;

      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (hasPubKey() != other.hasPubKey()) return false;
      if (hasPubKey()) {
        if (!getPubKey()
            .equals(other.getPubKey())) return false;
      }
      if (getVotingPower()
          != other.getVotingPower()) return false;
      if (getProposerPriority()
          != other.getProposerPriority()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      if (hasPubKey()) {
        hash = (37 * hash) + PUB_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getPubKey().hashCode();
      }
      hash = (37 * hash) + VOTING_POWER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVotingPower());
      hash = (37 * hash) + PROPOSER_PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProposerPriority());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Validator parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Validator parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Validator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Validator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Validator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Validator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Validator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Validator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Validator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Validator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Validator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Validator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Validator prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tendermint.types.Validator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tendermint.types.Validator)
        ValidatorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ValidatorOuterClass.internal_static_tendermint_types_Validator_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ValidatorOuterClass.internal_static_tendermint_types_Validator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Validator.class, Builder.class);
      }

      // Construct using tendermint.types.ValidatorOuterClass.Validator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        address_ = com.google.protobuf.ByteString.EMPTY;

        if (pubKeyBuilder_ == null) {
          pubKey_ = null;
        } else {
          pubKey_ = null;
          pubKeyBuilder_ = null;
        }
        votingPower_ = 0L;

        proposerPriority_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ValidatorOuterClass.internal_static_tendermint_types_Validator_descriptor;
      }

      @Override
      public Validator getDefaultInstanceForType() {
        return Validator.getDefaultInstance();
      }

      @Override
      public Validator build() {
        Validator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Validator buildPartial() {
        Validator result = new Validator(this);
        result.address_ = address_;
        if (pubKeyBuilder_ == null) {
          result.pubKey_ = pubKey_;
        } else {
          result.pubKey_ = pubKeyBuilder_.build();
        }
        result.votingPower_ = votingPower_;
        result.proposerPriority_ = proposerPriority_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Validator) {
          return mergeFrom((Validator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Validator other) {
        if (other == Validator.getDefaultInstance()) return this;
        if (other.getAddress() != com.google.protobuf.ByteString.EMPTY) {
          setAddress(other.getAddress());
        }
        if (other.hasPubKey()) {
          mergePubKey(other.getPubKey());
        }
        if (other.getVotingPower() != 0L) {
          setVotingPower(other.getVotingPower());
        }
        if (other.getProposerPriority() != 0L) {
          setProposerPriority(other.getProposerPriority());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Validator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Validator) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes address = 1;</code>
       * @return The address.
       */
      @Override
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      /**
       * <code>bytes address = 1;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }

      private tendermint.crypto.Keys.PublicKey pubKey_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tendermint.crypto.Keys.PublicKey, tendermint.crypto.Keys.PublicKey.Builder, tendermint.crypto.Keys.PublicKeyOrBuilder> pubKeyBuilder_;
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
       * @return Whether the pubKey field is set.
       */
      public boolean hasPubKey() {
        return pubKeyBuilder_ != null || pubKey_ != null;
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
       * @return The pubKey.
       */
      public tendermint.crypto.Keys.PublicKey getPubKey() {
        if (pubKeyBuilder_ == null) {
          return pubKey_ == null ? tendermint.crypto.Keys.PublicKey.getDefaultInstance() : pubKey_;
        } else {
          return pubKeyBuilder_.getMessage();
        }
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setPubKey(tendermint.crypto.Keys.PublicKey value) {
        if (pubKeyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pubKey_ = value;
          onChanged();
        } else {
          pubKeyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setPubKey(
          tendermint.crypto.Keys.PublicKey.Builder builderForValue) {
        if (pubKeyBuilder_ == null) {
          pubKey_ = builderForValue.build();
          onChanged();
        } else {
          pubKeyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergePubKey(tendermint.crypto.Keys.PublicKey value) {
        if (pubKeyBuilder_ == null) {
          if (pubKey_ != null) {
            pubKey_ =
              tendermint.crypto.Keys.PublicKey.newBuilder(pubKey_).mergeFrom(value).buildPartial();
          } else {
            pubKey_ = value;
          }
          onChanged();
        } else {
          pubKeyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearPubKey() {
        if (pubKeyBuilder_ == null) {
          pubKey_ = null;
          onChanged();
        } else {
          pubKey_ = null;
          pubKeyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
       */
      public tendermint.crypto.Keys.PublicKey.Builder getPubKeyBuilder() {
        
        onChanged();
        return getPubKeyFieldBuilder().getBuilder();
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
       */
      public tendermint.crypto.Keys.PublicKeyOrBuilder getPubKeyOrBuilder() {
        if (pubKeyBuilder_ != null) {
          return pubKeyBuilder_.getMessageOrBuilder();
        } else {
          return pubKey_ == null ?
              tendermint.crypto.Keys.PublicKey.getDefaultInstance() : pubKey_;
        }
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 2 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tendermint.crypto.Keys.PublicKey, tendermint.crypto.Keys.PublicKey.Builder, tendermint.crypto.Keys.PublicKeyOrBuilder> 
          getPubKeyFieldBuilder() {
        if (pubKeyBuilder_ == null) {
          pubKeyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tendermint.crypto.Keys.PublicKey, tendermint.crypto.Keys.PublicKey.Builder, tendermint.crypto.Keys.PublicKeyOrBuilder>(
                  getPubKey(),
                  getParentForChildren(),
                  isClean());
          pubKey_ = null;
        }
        return pubKeyBuilder_;
      }

      private long votingPower_ ;
      /**
       * <code>int64 voting_power = 3;</code>
       * @return The votingPower.
       */
      @Override
      public long getVotingPower() {
        return votingPower_;
      }
      /**
       * <code>int64 voting_power = 3;</code>
       * @param value The votingPower to set.
       * @return This builder for chaining.
       */
      public Builder setVotingPower(long value) {
        
        votingPower_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 voting_power = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVotingPower() {
        
        votingPower_ = 0L;
        onChanged();
        return this;
      }

      private long proposerPriority_ ;
      /**
       * <code>int64 proposer_priority = 4;</code>
       * @return The proposerPriority.
       */
      @Override
      public long getProposerPriority() {
        return proposerPriority_;
      }
      /**
       * <code>int64 proposer_priority = 4;</code>
       * @param value The proposerPriority to set.
       * @return This builder for chaining.
       */
      public Builder setProposerPriority(long value) {
        
        proposerPriority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 proposer_priority = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearProposerPriority() {
        
        proposerPriority_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tendermint.types.Validator)
    }

    // @@protoc_insertion_point(class_scope:tendermint.types.Validator)
    private static final Validator DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Validator();
    }

    public static Validator getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Validator>
        PARSER = new com.google.protobuf.AbstractParser<Validator>() {
      @Override
      public Validator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Validator(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Validator> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Validator> getParserForType() {
      return PARSER;
    }

    @Override
    public Validator getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SimpleValidatorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tendermint.types.SimpleValidator)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
     * @return Whether the pubKey field is set.
     */
    boolean hasPubKey();
    /**
     * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
     * @return The pubKey.
     */
    tendermint.crypto.Keys.PublicKey getPubKey();
    /**
     * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
     */
    tendermint.crypto.Keys.PublicKeyOrBuilder getPubKeyOrBuilder();

    /**
     * <code>int64 voting_power = 2;</code>
     * @return The votingPower.
     */
    long getVotingPower();
  }
  /**
   * Protobuf type {@code tendermint.types.SimpleValidator}
   */
  public static final class SimpleValidator extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tendermint.types.SimpleValidator)
      SimpleValidatorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimpleValidator.newBuilder() to construct.
    private SimpleValidator(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleValidator() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SimpleValidator();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleValidator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tendermint.crypto.Keys.PublicKey.Builder subBuilder = null;
              if (pubKey_ != null) {
                subBuilder = pubKey_.toBuilder();
              }
              pubKey_ = input.readMessage(tendermint.crypto.Keys.PublicKey.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pubKey_);
                pubKey_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              votingPower_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ValidatorOuterClass.internal_static_tendermint_types_SimpleValidator_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ValidatorOuterClass.internal_static_tendermint_types_SimpleValidator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SimpleValidator.class, Builder.class);
    }

    public static final int PUB_KEY_FIELD_NUMBER = 1;
    private tendermint.crypto.Keys.PublicKey pubKey_;
    /**
     * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
     * @return Whether the pubKey field is set.
     */
    @Override
    public boolean hasPubKey() {
      return pubKey_ != null;
    }
    /**
     * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
     * @return The pubKey.
     */
    @Override
    public tendermint.crypto.Keys.PublicKey getPubKey() {
      return pubKey_ == null ? tendermint.crypto.Keys.PublicKey.getDefaultInstance() : pubKey_;
    }
    /**
     * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
     */
    @Override
    public tendermint.crypto.Keys.PublicKeyOrBuilder getPubKeyOrBuilder() {
      return getPubKey();
    }

    public static final int VOTING_POWER_FIELD_NUMBER = 2;
    private long votingPower_;
    /**
     * <code>int64 voting_power = 2;</code>
     * @return The votingPower.
     */
    @Override
    public long getVotingPower() {
      return votingPower_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pubKey_ != null) {
        output.writeMessage(1, getPubKey());
      }
      if (votingPower_ != 0L) {
        output.writeInt64(2, votingPower_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pubKey_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPubKey());
      }
      if (votingPower_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, votingPower_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SimpleValidator)) {
        return super.equals(obj);
      }
      SimpleValidator other = (SimpleValidator) obj;

      if (hasPubKey() != other.hasPubKey()) return false;
      if (hasPubKey()) {
        if (!getPubKey()
            .equals(other.getPubKey())) return false;
      }
      if (getVotingPower()
          != other.getVotingPower()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPubKey()) {
        hash = (37 * hash) + PUB_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getPubKey().hashCode();
      }
      hash = (37 * hash) + VOTING_POWER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVotingPower());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SimpleValidator parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleValidator parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleValidator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleValidator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleValidator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleValidator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleValidator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SimpleValidator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SimpleValidator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SimpleValidator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SimpleValidator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SimpleValidator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SimpleValidator prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tendermint.types.SimpleValidator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tendermint.types.SimpleValidator)
        SimpleValidatorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ValidatorOuterClass.internal_static_tendermint_types_SimpleValidator_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ValidatorOuterClass.internal_static_tendermint_types_SimpleValidator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SimpleValidator.class, Builder.class);
      }

      // Construct using tendermint.types.ValidatorOuterClass.SimpleValidator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (pubKeyBuilder_ == null) {
          pubKey_ = null;
        } else {
          pubKey_ = null;
          pubKeyBuilder_ = null;
        }
        votingPower_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ValidatorOuterClass.internal_static_tendermint_types_SimpleValidator_descriptor;
      }

      @Override
      public SimpleValidator getDefaultInstanceForType() {
        return SimpleValidator.getDefaultInstance();
      }

      @Override
      public SimpleValidator build() {
        SimpleValidator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SimpleValidator buildPartial() {
        SimpleValidator result = new SimpleValidator(this);
        if (pubKeyBuilder_ == null) {
          result.pubKey_ = pubKey_;
        } else {
          result.pubKey_ = pubKeyBuilder_.build();
        }
        result.votingPower_ = votingPower_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SimpleValidator) {
          return mergeFrom((SimpleValidator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SimpleValidator other) {
        if (other == SimpleValidator.getDefaultInstance()) return this;
        if (other.hasPubKey()) {
          mergePubKey(other.getPubKey());
        }
        if (other.getVotingPower() != 0L) {
          setVotingPower(other.getVotingPower());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SimpleValidator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SimpleValidator) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private tendermint.crypto.Keys.PublicKey pubKey_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tendermint.crypto.Keys.PublicKey, tendermint.crypto.Keys.PublicKey.Builder, tendermint.crypto.Keys.PublicKeyOrBuilder> pubKeyBuilder_;
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
       * @return Whether the pubKey field is set.
       */
      public boolean hasPubKey() {
        return pubKeyBuilder_ != null || pubKey_ != null;
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
       * @return The pubKey.
       */
      public tendermint.crypto.Keys.PublicKey getPubKey() {
        if (pubKeyBuilder_ == null) {
          return pubKey_ == null ? tendermint.crypto.Keys.PublicKey.getDefaultInstance() : pubKey_;
        } else {
          return pubKeyBuilder_.getMessage();
        }
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
       */
      public Builder setPubKey(tendermint.crypto.Keys.PublicKey value) {
        if (pubKeyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pubKey_ = value;
          onChanged();
        } else {
          pubKeyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
       */
      public Builder setPubKey(
          tendermint.crypto.Keys.PublicKey.Builder builderForValue) {
        if (pubKeyBuilder_ == null) {
          pubKey_ = builderForValue.build();
          onChanged();
        } else {
          pubKeyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
       */
      public Builder mergePubKey(tendermint.crypto.Keys.PublicKey value) {
        if (pubKeyBuilder_ == null) {
          if (pubKey_ != null) {
            pubKey_ =
              tendermint.crypto.Keys.PublicKey.newBuilder(pubKey_).mergeFrom(value).buildPartial();
          } else {
            pubKey_ = value;
          }
          onChanged();
        } else {
          pubKeyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
       */
      public Builder clearPubKey() {
        if (pubKeyBuilder_ == null) {
          pubKey_ = null;
          onChanged();
        } else {
          pubKey_ = null;
          pubKeyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
       */
      public tendermint.crypto.Keys.PublicKey.Builder getPubKeyBuilder() {
        
        onChanged();
        return getPubKeyFieldBuilder().getBuilder();
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
       */
      public tendermint.crypto.Keys.PublicKeyOrBuilder getPubKeyOrBuilder() {
        if (pubKeyBuilder_ != null) {
          return pubKeyBuilder_.getMessageOrBuilder();
        } else {
          return pubKey_ == null ?
              tendermint.crypto.Keys.PublicKey.getDefaultInstance() : pubKey_;
        }
      }
      /**
       * <code>.tendermint.crypto.PublicKey pub_key = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tendermint.crypto.Keys.PublicKey, tendermint.crypto.Keys.PublicKey.Builder, tendermint.crypto.Keys.PublicKeyOrBuilder> 
          getPubKeyFieldBuilder() {
        if (pubKeyBuilder_ == null) {
          pubKeyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tendermint.crypto.Keys.PublicKey, tendermint.crypto.Keys.PublicKey.Builder, tendermint.crypto.Keys.PublicKeyOrBuilder>(
                  getPubKey(),
                  getParentForChildren(),
                  isClean());
          pubKey_ = null;
        }
        return pubKeyBuilder_;
      }

      private long votingPower_ ;
      /**
       * <code>int64 voting_power = 2;</code>
       * @return The votingPower.
       */
      @Override
      public long getVotingPower() {
        return votingPower_;
      }
      /**
       * <code>int64 voting_power = 2;</code>
       * @param value The votingPower to set.
       * @return This builder for chaining.
       */
      public Builder setVotingPower(long value) {
        
        votingPower_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 voting_power = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVotingPower() {
        
        votingPower_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tendermint.types.SimpleValidator)
    }

    // @@protoc_insertion_point(class_scope:tendermint.types.SimpleValidator)
    private static final SimpleValidator DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SimpleValidator();
    }

    public static SimpleValidator getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimpleValidator>
        PARSER = new com.google.protobuf.AbstractParser<SimpleValidator>() {
      @Override
      public SimpleValidator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimpleValidator(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimpleValidator> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SimpleValidator> getParserForType() {
      return PARSER;
    }

    @Override
    public SimpleValidator getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tendermint_types_ValidatorSet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tendermint_types_ValidatorSet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tendermint_types_Validator_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tendermint_types_Validator_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tendermint_types_SimpleValidator_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tendermint_types_SimpleValidator_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n tendermint/types/validator.proto\022\020tend" +
      "ermint.types\032\024gogoproto/gogo.proto\032\034tend" +
      "ermint/crypto/keys.proto\"\212\001\n\014ValidatorSe" +
      "t\022/\n\nvalidators\030\001 \003(\0132\033.tendermint.types" +
      ".Validator\022-\n\010proposer\030\002 \001(\0132\033.tendermin" +
      "t.types.Validator\022\032\n\022total_voting_power\030" +
      "\003 \001(\003\"\202\001\n\tValidator\022\017\n\007address\030\001 \001(\014\0223\n\007" +
      "pub_key\030\002 \001(\0132\034.tendermint.crypto.Public" +
      "KeyB\004\310\336\037\000\022\024\n\014voting_power\030\003 \001(\003\022\031\n\021propo" +
      "ser_priority\030\004 \001(\003\"V\n\017SimpleValidator\022-\n" +
      "\007pub_key\030\001 \001(\0132\034.tendermint.crypto.Publi" +
      "cKey\022\024\n\014voting_power\030\002 \001(\003B9Z7github.com" +
      "/tendermint/tendermint/proto/tendermint/" +
      "typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf2.GoGoProtos.getDescriptor(),
          tendermint.crypto.Keys.getDescriptor(),
        });
    internal_static_tendermint_types_ValidatorSet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tendermint_types_ValidatorSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tendermint_types_ValidatorSet_descriptor,
        new String[] { "Validators", "Proposer", "TotalVotingPower", });
    internal_static_tendermint_types_Validator_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tendermint_types_Validator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tendermint_types_Validator_descriptor,
        new String[] { "Address", "PubKey", "VotingPower", "ProposerPriority", });
    internal_static_tendermint_types_SimpleValidator_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tendermint_types_SimpleValidator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tendermint_types_SimpleValidator_descriptor,
        new String[] { "PubKey", "VotingPower", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf2.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf2.GoGoProtos.getDescriptor();
    tendermint.crypto.Keys.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
