// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sentinel/types/v1/bandwidth.proto

package sentinel.types.v1;

public final class BandwidthOuterClass {
  private BandwidthOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BandwidthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sentinel.types.v1.Bandwidth)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string upload = 1[json_name = "upload", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     */
    java.lang.String getUpload();
    /**
     * <code>string upload = 1[json_name = "upload", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     */
    com.google.protobuf.ByteString
        getUploadBytes();

    /**
     * <code>string download = 2[json_name = "download", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     */
    java.lang.String getDownload();
    /**
     * <code>string download = 2[json_name = "download", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     */
    com.google.protobuf.ByteString
        getDownloadBytes();
  }
  /**
   * Protobuf type {@code sentinel.types.v1.Bandwidth}
   */
  public  static final class Bandwidth extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sentinel.types.v1.Bandwidth)
      BandwidthOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Bandwidth.newBuilder() to construct.
    private Bandwidth(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Bandwidth() {
      upload_ = "";
      download_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Bandwidth(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              upload_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              download_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.types.v1.BandwidthOuterClass.internal_static_sentinel_types_v1_Bandwidth_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.types.v1.BandwidthOuterClass.internal_static_sentinel_types_v1_Bandwidth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.types.v1.BandwidthOuterClass.Bandwidth.class, sentinel.types.v1.BandwidthOuterClass.Bandwidth.Builder.class);
    }

    public static final int UPLOAD_FIELD_NUMBER = 1;
    private volatile java.lang.Object upload_;
    /**
     * <code>string upload = 1[json_name = "upload", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     */
    public java.lang.String getUpload() {
      java.lang.Object ref = upload_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        upload_ = s;
        return s;
      }
    }
    /**
     * <code>string upload = 1[json_name = "upload", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     */
    public com.google.protobuf.ByteString
        getUploadBytes() {
      java.lang.Object ref = upload_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        upload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOWNLOAD_FIELD_NUMBER = 2;
    private volatile java.lang.Object download_;
    /**
     * <code>string download = 2[json_name = "download", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     */
    public java.lang.String getDownload() {
      java.lang.Object ref = download_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        download_ = s;
        return s;
      }
    }
    /**
     * <code>string download = 2[json_name = "download", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     */
    public com.google.protobuf.ByteString
        getDownloadBytes() {
      java.lang.Object ref = download_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        download_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUploadBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, upload_);
      }
      if (!getDownloadBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, download_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUploadBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, upload_);
      }
      if (!getDownloadBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, download_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sentinel.types.v1.BandwidthOuterClass.Bandwidth)) {
        return super.equals(obj);
      }
      sentinel.types.v1.BandwidthOuterClass.Bandwidth other = (sentinel.types.v1.BandwidthOuterClass.Bandwidth) obj;

      boolean result = true;
      result = result && getUpload()
          .equals(other.getUpload());
      result = result && getDownload()
          .equals(other.getDownload());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UPLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getUpload().hashCode();
      hash = (37 * hash) + DOWNLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getDownload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sentinel.types.v1.BandwidthOuterClass.Bandwidth prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sentinel.types.v1.Bandwidth}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sentinel.types.v1.Bandwidth)
        sentinel.types.v1.BandwidthOuterClass.BandwidthOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sentinel.types.v1.BandwidthOuterClass.internal_static_sentinel_types_v1_Bandwidth_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sentinel.types.v1.BandwidthOuterClass.internal_static_sentinel_types_v1_Bandwidth_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sentinel.types.v1.BandwidthOuterClass.Bandwidth.class, sentinel.types.v1.BandwidthOuterClass.Bandwidth.Builder.class);
      }

      // Construct using sentinel.types.v1.BandwidthOuterClass.Bandwidth.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        upload_ = "";

        download_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sentinel.types.v1.BandwidthOuterClass.internal_static_sentinel_types_v1_Bandwidth_descriptor;
      }

      @java.lang.Override
      public sentinel.types.v1.BandwidthOuterClass.Bandwidth getDefaultInstanceForType() {
        return sentinel.types.v1.BandwidthOuterClass.Bandwidth.getDefaultInstance();
      }

      @java.lang.Override
      public sentinel.types.v1.BandwidthOuterClass.Bandwidth build() {
        sentinel.types.v1.BandwidthOuterClass.Bandwidth result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sentinel.types.v1.BandwidthOuterClass.Bandwidth buildPartial() {
        sentinel.types.v1.BandwidthOuterClass.Bandwidth result = new sentinel.types.v1.BandwidthOuterClass.Bandwidth(this);
        result.upload_ = upload_;
        result.download_ = download_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sentinel.types.v1.BandwidthOuterClass.Bandwidth) {
          return mergeFrom((sentinel.types.v1.BandwidthOuterClass.Bandwidth)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sentinel.types.v1.BandwidthOuterClass.Bandwidth other) {
        if (other == sentinel.types.v1.BandwidthOuterClass.Bandwidth.getDefaultInstance()) return this;
        if (!other.getUpload().isEmpty()) {
          upload_ = other.upload_;
          onChanged();
        }
        if (!other.getDownload().isEmpty()) {
          download_ = other.download_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sentinel.types.v1.BandwidthOuterClass.Bandwidth parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sentinel.types.v1.BandwidthOuterClass.Bandwidth) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object upload_ = "";
      /**
       * <code>string upload = 1[json_name = "upload", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       */
      public java.lang.String getUpload() {
        java.lang.Object ref = upload_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          upload_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string upload = 1[json_name = "upload", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       */
      public com.google.protobuf.ByteString
          getUploadBytes() {
        java.lang.Object ref = upload_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          upload_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string upload = 1[json_name = "upload", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       */
      public Builder setUpload(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        upload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string upload = 1[json_name = "upload", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       */
      public Builder clearUpload() {
        
        upload_ = getDefaultInstance().getUpload();
        onChanged();
        return this;
      }
      /**
       * <code>string upload = 1[json_name = "upload", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       */
      public Builder setUploadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        upload_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object download_ = "";
      /**
       * <code>string download = 2[json_name = "download", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       */
      public java.lang.String getDownload() {
        java.lang.Object ref = download_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          download_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string download = 2[json_name = "download", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       */
      public com.google.protobuf.ByteString
          getDownloadBytes() {
        java.lang.Object ref = download_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          download_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string download = 2[json_name = "download", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       */
      public Builder setDownload(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        download_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string download = 2[json_name = "download", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       */
      public Builder clearDownload() {
        
        download_ = getDefaultInstance().getDownload();
        onChanged();
        return this;
      }
      /**
       * <code>string download = 2[json_name = "download", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       */
      public Builder setDownloadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        download_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sentinel.types.v1.Bandwidth)
    }

    // @@protoc_insertion_point(class_scope:sentinel.types.v1.Bandwidth)
    private static final sentinel.types.v1.BandwidthOuterClass.Bandwidth DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sentinel.types.v1.BandwidthOuterClass.Bandwidth();
    }

    public static sentinel.types.v1.BandwidthOuterClass.Bandwidth getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Bandwidth>
        PARSER = new com.google.protobuf.AbstractParser<Bandwidth>() {
      @java.lang.Override
      public Bandwidth parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Bandwidth(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Bandwidth> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bandwidth> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sentinel.types.v1.BandwidthOuterClass.Bandwidth getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_types_v1_Bandwidth_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentinel_types_v1_Bandwidth_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!sentinel/types/v1/bandwidth.proto\022\021sen" +
      "tinel.types.v1\032\024gogoproto/gogo.proto\"\237\001\n" +
      "\tBandwidth\022F\n\006upload\030\001 \001(\tB.\310\336\037\000\332\336\037&gith" +
      "ub.com/cosmos/cosmos-sdk/types.IntR\006uplo" +
      "ad\022J\n\010download\030\002 \001(\tB.\310\336\037\000\332\336\037&github.com" +
      "/cosmos/cosmos-sdk/types.IntR\010downloadB0" +
      "Z&github.com/sentinel-official/hub/types" +
      "\310\341\036\000\250\342\036\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf2.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_sentinel_types_v1_Bandwidth_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sentinel_types_v1_Bandwidth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentinel_types_v1_Bandwidth_descriptor,
        new java.lang.String[] { "Upload", "Download", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf2.GoGoProtos.customtype);
    registry.add(com.google.protobuf2.GoGoProtos.equalAll);
    registry.add(com.google.protobuf2.GoGoProtos.goprotoGettersAll);
    registry.add(com.google.protobuf2.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf2.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
