// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/version/types.proto

package tendermint.version;

public final class Types {
  private Types() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tendermint.version.App)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 protocol = 1;</code>
     * @return The protocol.
     */
    long getProtocol();

    /**
     * <code>string software = 2;</code>
     * @return The software.
     */
    String getSoftware();
    /**
     * <code>string software = 2;</code>
     * @return The bytes for software.
     */
    com.google.protobuf.ByteString
        getSoftwareBytes();
  }
  /**
   * <pre>
   * App includes the protocol and software version for the application.
   * This information is included in ResponseInfo. The App.Protocol can be
   * updated in ResponseEndBlock.
   * </pre>
   *
   * Protobuf type {@code tendermint.version.App}
   */
  public static final class App extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tendermint.version.App)
      AppOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use App.newBuilder() to construct.
    private App(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private App() {
      software_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new App();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private App(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              protocol_ = input.readUInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              software_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Types.internal_static_tendermint_version_App_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Types.internal_static_tendermint_version_App_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              App.class, Builder.class);
    }

    public static final int PROTOCOL_FIELD_NUMBER = 1;
    private long protocol_;
    /**
     * <code>uint64 protocol = 1;</code>
     * @return The protocol.
     */
    @Override
    public long getProtocol() {
      return protocol_;
    }

    public static final int SOFTWARE_FIELD_NUMBER = 2;
    private volatile Object software_;
    /**
     * <code>string software = 2;</code>
     * @return The software.
     */
    @Override
    public String getSoftware() {
      Object ref = software_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        software_ = s;
        return s;
      }
    }
    /**
     * <code>string software = 2;</code>
     * @return The bytes for software.
     */
    @Override
    public com.google.protobuf.ByteString
        getSoftwareBytes() {
      Object ref = software_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        software_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (protocol_ != 0L) {
        output.writeUInt64(1, protocol_);
      }
      if (!getSoftwareBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, software_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (protocol_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, protocol_);
      }
      if (!getSoftwareBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, software_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof App)) {
        return super.equals(obj);
      }
      App other = (App) obj;

      if (getProtocol()
          != other.getProtocol()) return false;
      if (!getSoftware()
          .equals(other.getSoftware())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProtocol());
      hash = (37 * hash) + SOFTWARE_FIELD_NUMBER;
      hash = (53 * hash) + getSoftware().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static App parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static App parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static App parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static App parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static App parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static App parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static App parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static App parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static App parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static App parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static App parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static App parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(App prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * App includes the protocol and software version for the application.
     * This information is included in ResponseInfo. The App.Protocol can be
     * updated in ResponseEndBlock.
     * </pre>
     *
     * Protobuf type {@code tendermint.version.App}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tendermint.version.App)
        AppOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Types.internal_static_tendermint_version_App_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Types.internal_static_tendermint_version_App_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                App.class, Builder.class);
      }

      // Construct using tendermint.version.Types.App.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        protocol_ = 0L;

        software_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Types.internal_static_tendermint_version_App_descriptor;
      }

      @Override
      public App getDefaultInstanceForType() {
        return App.getDefaultInstance();
      }

      @Override
      public App build() {
        App result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public App buildPartial() {
        App result = new App(this);
        result.protocol_ = protocol_;
        result.software_ = software_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof App) {
          return mergeFrom((App)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(App other) {
        if (other == App.getDefaultInstance()) return this;
        if (other.getProtocol() != 0L) {
          setProtocol(other.getProtocol());
        }
        if (!other.getSoftware().isEmpty()) {
          software_ = other.software_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        App parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (App) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long protocol_ ;
      /**
       * <code>uint64 protocol = 1;</code>
       * @return The protocol.
       */
      @Override
      public long getProtocol() {
        return protocol_;
      }
      /**
       * <code>uint64 protocol = 1;</code>
       * @param value The protocol to set.
       * @return This builder for chaining.
       */
      public Builder setProtocol(long value) {
        
        protocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 protocol = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocol() {
        
        protocol_ = 0L;
        onChanged();
        return this;
      }

      private Object software_ = "";
      /**
       * <code>string software = 2;</code>
       * @return The software.
       */
      public String getSoftware() {
        Object ref = software_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          software_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string software = 2;</code>
       * @return The bytes for software.
       */
      public com.google.protobuf.ByteString
          getSoftwareBytes() {
        Object ref = software_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          software_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string software = 2;</code>
       * @param value The software to set.
       * @return This builder for chaining.
       */
      public Builder setSoftware(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        software_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string software = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSoftware() {
        
        software_ = getDefaultInstance().getSoftware();
        onChanged();
        return this;
      }
      /**
       * <code>string software = 2;</code>
       * @param value The bytes for software to set.
       * @return This builder for chaining.
       */
      public Builder setSoftwareBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        software_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tendermint.version.App)
    }

    // @@protoc_insertion_point(class_scope:tendermint.version.App)
    private static final App DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new App();
    }

    public static App getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<App>
        PARSER = new com.google.protobuf.AbstractParser<App>() {
      @Override
      public App parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new App(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<App> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<App> getParserForType() {
      return PARSER;
    }

    @Override
    public App getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConsensusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tendermint.version.Consensus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 block = 1;</code>
     * @return The block.
     */
    long getBlock();

    /**
     * <code>uint64 app = 2;</code>
     * @return The app.
     */
    long getApp();
  }
  /**
   * <pre>
   * Consensus captures the consensus rules for processing a block in the blockchain,
   * including all blockchain data structures and the rules of the application's
   * state transition machine.
   * </pre>
   *
   * Protobuf type {@code tendermint.version.Consensus}
   */
  public static final class Consensus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tendermint.version.Consensus)
      ConsensusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Consensus.newBuilder() to construct.
    private Consensus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Consensus() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Consensus();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Consensus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              block_ = input.readUInt64();
              break;
            }
            case 16: {

              app_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Types.internal_static_tendermint_version_Consensus_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Types.internal_static_tendermint_version_Consensus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Consensus.class, Builder.class);
    }

    public static final int BLOCK_FIELD_NUMBER = 1;
    private long block_;
    /**
     * <code>uint64 block = 1;</code>
     * @return The block.
     */
    @Override
    public long getBlock() {
      return block_;
    }

    public static final int APP_FIELD_NUMBER = 2;
    private long app_;
    /**
     * <code>uint64 app = 2;</code>
     * @return The app.
     */
    @Override
    public long getApp() {
      return app_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (block_ != 0L) {
        output.writeUInt64(1, block_);
      }
      if (app_ != 0L) {
        output.writeUInt64(2, app_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (block_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, block_);
      }
      if (app_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, app_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Consensus)) {
        return super.equals(obj);
      }
      Consensus other = (Consensus) obj;

      if (getBlock()
          != other.getBlock()) return false;
      if (getApp()
          != other.getApp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlock());
      hash = (37 * hash) + APP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getApp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Consensus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Consensus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Consensus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Consensus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Consensus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Consensus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Consensus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Consensus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Consensus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Consensus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Consensus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Consensus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Consensus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Consensus captures the consensus rules for processing a block in the blockchain,
     * including all blockchain data structures and the rules of the application's
     * state transition machine.
     * </pre>
     *
     * Protobuf type {@code tendermint.version.Consensus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tendermint.version.Consensus)
        ConsensusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Types.internal_static_tendermint_version_Consensus_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Types.internal_static_tendermint_version_Consensus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Consensus.class, Builder.class);
      }

      // Construct using tendermint.version.Types.Consensus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        block_ = 0L;

        app_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Types.internal_static_tendermint_version_Consensus_descriptor;
      }

      @Override
      public Consensus getDefaultInstanceForType() {
        return Consensus.getDefaultInstance();
      }

      @Override
      public Consensus build() {
        Consensus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Consensus buildPartial() {
        Consensus result = new Consensus(this);
        result.block_ = block_;
        result.app_ = app_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Consensus) {
          return mergeFrom((Consensus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Consensus other) {
        if (other == Consensus.getDefaultInstance()) return this;
        if (other.getBlock() != 0L) {
          setBlock(other.getBlock());
        }
        if (other.getApp() != 0L) {
          setApp(other.getApp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Consensus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Consensus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long block_ ;
      /**
       * <code>uint64 block = 1;</code>
       * @return The block.
       */
      @Override
      public long getBlock() {
        return block_;
      }
      /**
       * <code>uint64 block = 1;</code>
       * @param value The block to set.
       * @return This builder for chaining.
       */
      public Builder setBlock(long value) {
        
        block_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 block = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlock() {
        
        block_ = 0L;
        onChanged();
        return this;
      }

      private long app_ ;
      /**
       * <code>uint64 app = 2;</code>
       * @return The app.
       */
      @Override
      public long getApp() {
        return app_;
      }
      /**
       * <code>uint64 app = 2;</code>
       * @param value The app to set.
       * @return This builder for chaining.
       */
      public Builder setApp(long value) {
        
        app_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 app = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearApp() {
        
        app_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tendermint.version.Consensus)
    }

    // @@protoc_insertion_point(class_scope:tendermint.version.Consensus)
    private static final Consensus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Consensus();
    }

    public static Consensus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Consensus>
        PARSER = new com.google.protobuf.AbstractParser<Consensus>() {
      @Override
      public Consensus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Consensus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Consensus> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Consensus> getParserForType() {
      return PARSER;
    }

    @Override
    public Consensus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tendermint_version_App_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tendermint_version_App_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tendermint_version_Consensus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tendermint_version_Consensus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036tendermint/version/types.proto\022\022tender" +
      "mint.version\032\024gogoproto/gogo.proto\")\n\003Ap" +
      "p\022\020\n\010protocol\030\001 \001(\004\022\020\n\010software\030\002 \001(\t\"-\n" +
      "\tConsensus\022\r\n\005block\030\001 \001(\004\022\013\n\003app\030\002 \001(\004:\004" +
      "\350\240\037\001B;Z9github.com/tendermint/tendermint" +
      "/proto/tendermint/versionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf2.GoGoProtos.getDescriptor(),
        });
    internal_static_tendermint_version_App_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tendermint_version_App_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tendermint_version_App_descriptor,
        new String[] { "Protocol", "Software", });
    internal_static_tendermint_version_Consensus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tendermint_version_Consensus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tendermint_version_Consensus_descriptor,
        new String[] { "Block", "App", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf2.GoGoProtos.equal);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf2.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
